Attemt #2 of fixing mingw and msys compile, now ACE almost builds, just need to fix the "Undefined reference to Netbios@4" linker error
Signed-off-by: Subv2112 <s.v.h21@hotmail.com>